### PR TITLE
Rewrote Reading page to reflect new design

### LINKED ISSUE #11: Update 'Reading E-mail' page
It feels like most of this should be rewritten.

### PR DESCRIPTION
**Pull request by artbristol**
Also updated some of the English to be easier for non-native speakers (hopefully)

Fixes #11

### CODE REVIEW

**Comment by obra** [comment]
Do the keyboard shortcuts not work when running K-9 on ChromeOS?

**Comment by cketti** [comment]
> Do the keyboard shortcuts not work when running K-9 on ChromeOS?

They do. And some people use them. So we should probably leave the description in the documentation.

**Comment by artbristol** [comment]
I also think some explanation of how deletion works (IMAP expunging, Trash etc) is in order, but I'm not sure if this is the correct page for it.

**Review by cketti — APPROVED** [review]
Overall, this page isn't great. However, with your edits it is strictly better than it was before :+1:

**Comment by cketti** [comment]
We should probably create a new page like "managing mail" that explains the different actions in a bit more depth. I created issue #46 for that.

**Pull request merged**
